# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
 use_frameworks!

target 'wiActsInterview' do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'CryptoSwift'
end
